import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Bell, Droplets, HeartHandshake, LayoutDashboard, LogOut, Menu, Settings, ShieldAlert, Users, WalletCards, X } from "lucide-react";
import "./styles.css";

const configuredApi = import.meta.env.VITE_API_URL;
const API = `${configuredApi ? configuredApi.replace(/\/$/, "") : ""}/api`;
const navItems = [
  ["dashboard", "Dashboard", LayoutDashboard], ["users", "All users", Users], ["sos", "SOS alerts", ShieldAlert], ["blood", "Blood requests", Droplets], ["volunteers", "Volunteers", HeartHandshake], ["plans", "Plans", WalletCards], ["notifications", "Notifications", Bell], ["settings", "Settings", Settings],
];

async function request(path, options = {}, token) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token || ""}`, ...(options.headers || {}) } });
  const body = await response.json();
  if (!response.ok || body.success === false) throw new Error(body.message || "Request failed");
  return body.data;
}

function Login({ onLogin }) {
  const [email, setEmail] = useState("admin@pahelfoundation.org"); const [password, setPassword] = useState("PahelAdmin#2026"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { const data = await request("/admin/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); onLogin(data.token); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <main className="login-page"><div className="login-art"><div className="mark">PF</div><p className="kicker">PAHEL FOUNDATION</p><h1>Care is a system, not a moment.</h1><p>One operational view for every alert, volunteer, request, and contribution.</p></div><form className="login-card" onSubmit={submit}><p className="kicker">SECURE ADMIN ACCESS</p><h2>Welcome back</h2><p className="muted">Sign in with the single seeded administrator account.</p><label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" /></label><label>Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" /></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={loading}>{loading ? "Signing in…" : "Enter dashboard"}</button></form></main>;
}

function StatCard({ label, value, tone = "crimson" }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Activity size={18} /></div><p>{label}</p><strong>{value ?? 0}</strong></div>; }
function Table({ columns, rows }) { return <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(row) : row[column.key] || "—"}</td>)}</tr>) : <tr><td colSpan={columns.length} className="empty">No records yet</td></tr>}</tbody></table></div>; }

function Dashboard({ token }) { const [data, setData] = useState({}); useEffect(() => { request("/admin/dashboard", {}, token).then(setData).catch(() => undefined); }, [token]); return <><PageTitle eyebrow="OVERVIEW" title="Good morning, admin." subtitle="A clear view of the community response network." /><div className="stats-grid"><StatCard label="Total users" value={data.users} /><StatCard label="SOS alerts" value={data.sos_alerts} tone="rose" /><StatCard label="Open blood requests" value={data.open_blood_requests} tone="blue" /><StatCard label="Total donations" value={`₹${(data.total_donations_amount || 0).toLocaleString("en-IN")}`} tone="gold" /></div><div className="dashboard-grid"><section className="panel highlight"><p className="kicker">SAFETY PULSE</p><h3>Every alert deserves a visible response.</h3><p className="muted">Nearby dispatch, contact delivery, and status updates remain attached to each SOS record for accountability.</p><div className="pulse-line"><span /><span /><span /><span /><span /></div></section><section className="panel"><p className="kicker">VOLUNTEERS</p><div className="big-number">{data.approved_volunteers || 0}</div><p className="muted">approved community responders</p><div className="mini-row"><span>Pending review</span><b>{data.pending_volunteers || 0}</b></div></section></div></>; }
function PageTitle({ eyebrow, title, subtitle }) { return <div className="page-title"><p className="kicker">{eyebrow}</p><h2>{title}</h2><p className="muted">{subtitle}</p></div>; }

function DataPage({ title, eyebrow, endpoint, token, columns, subtitle }) { const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { setLoading(true); request(endpoint, {}, token).then((data) => setRows(data.items || data)).catch(() => setRows([])).finally(() => setLoading(false)); }, [endpoint, token]); return <><PageTitle eyebrow={eyebrow} title={title} subtitle={subtitle} /><div className="toolbar"><span className="muted">{loading ? "Refreshing live data…" : `${rows.length} records shown`}</span><button className="outline" onClick={() => request(endpoint, {}, token).then((data) => setRows(data.items || data))}>Refresh</button></div><Table columns={columns} rows={rows} /></>; }

function Volunteers({ token }) { const [rows, setRows] = useState([]); const load = () => request("/admin/volunteers", {}, token).then(setRows).catch(() => undefined); useEffect(load, [token]); const review = async (id, action) => { await request(`/admin/volunteers/${id}/${action}`, { method: "POST" }, token); load(); }; return <><PageTitle eyebrow="PEOPLE" title="Volunteer applications" subtitle="Review the people ready to show up for their community." /><Table columns={[{ key: "full_name", label: "Applicant" }, { key: "city", label: "City" }, { key: "reason", label: "Reason" }, { key: "status", label: "Status", render: (row) => <span className={`status ${row.status.toLowerCase()}`}>{row.status}</span> }, { key: "actions", label: "Actions", render: (row) => row.status === "PENDING" && <div className="actions"><button className="small-button" onClick={() => review(row.id, "approve")}>Approve</button><button className="small-button ghost" onClick={() => review(row.id, "reject")}>Reject</button></div> }]} rows={rows} /></>; }

function Notifications({ token }) { const [title, setTitle] = useState(""); const [message, setMessage] = useState(""); const [result, setResult] = useState(""); const send = async (event) => { event.preventDefault(); try { const data = await request("/admin/notifications/broadcast", { method: "POST", body: JSON.stringify({ title, message }) }, token); setResult(`Created for ${data.recipients} users.`); setTitle(""); setMessage(""); } catch (err) { setResult(err.message); } }; return <><PageTitle eyebrow="OUTREACH" title="Foundation notifications" subtitle="Send an announcement to every active user and save it to their inbox." /><form className="panel form-panel" onSubmit={send}><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Community update" /></label><label>Message<textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write a clear, useful update…" /></label><button className="primary">Send announcement</button>{result && <p className="success">{result}</p>}</form></>; }

function SettingsPage({ token }) { const [form, setForm] = useState({ help_number: "", emergency_number: "", help_email: "", support_message: "" }); useEffect(() => { request("/admin/settings", {}, token).then((items) => setForm(items.find((item) => item.key === "contact") || form)).catch(() => undefined); }, [token]); const save = async (e) => { e.preventDefault(); await request("/admin/settings/contact", { method: "PUT", body: JSON.stringify(form) }, token); alert("Contact settings saved"); }; return <><PageTitle eyebrow="CONFIGURATION" title="Contact & help" subtitle="Keep the mobile experience current without a new release." /><form className="panel form-panel" onSubmit={save}>{Object.entries(form).filter(([key]) => key !== "key" && key !== "updated_at").map(([key, value]) => <label key={key}>{key.replaceAll("_", " ")}<input value={value || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<button className="primary">Save settings</button></form></>; }

function App() { const [token, setToken] = useState(""); const [page, setPage] = useState("dashboard"); const [mobileNav, setMobileNav] = useState(false); if (!token) return <Login onLogin={setToken} />; const item = navItems.find(([id]) => id === page); const Page = page === "dashboard" ? <Dashboard token={token} /> : page === "volunteers" ? <Volunteers token={token} /> : page === "notifications" ? <Notifications token={token} /> : page === "settings" ? <SettingsPage token={token} /> : <DataPage token={token} endpoint={`/admin/${page === "users" ? "users" : page === "sos" ? "sos" : page === "blood" ? "blood-requests" : page}`} title={item?.[1]} eyebrow="OPERATIONS" subtitle="Live records from the PAHEL FOUNDATION backend." columns={page === "users" ? [{ key: "name", label: "Name" }, { key: "mobile", label: "Mobile" }, { key: "volunteer_status", label: "Volunteer" }, { key: "created_at", label: "Joined" }] : page === "sos" ? [{ key: "user_name", label: "User" }, { key: "status", label: "Status" }, { key: "whatsapp_status", label: "WhatsApp" }, { key: "created_at", label: "Created" }] : page === "blood" ? [{ key: "patient_name", label: "Patient" }, { key: "blood_group", label: "Group" }, { key: "units", label: "Units" }, { key: "status", label: "Status" }] : [{ key: "name", label: "Name" }, { key: "status", label: "Status" }, { key: "amount", label: "Amount" }, { key: "created_at", label: "Created" }]} />; return <div className="app-shell"><aside className={mobileNav ? "sidebar open" : "sidebar"}><div className="brand"><div className="mark small">PF</div><div><b>PAHEL</b><span>FOUNDATION</span></div><button className="close-nav" onClick={() => setMobileNav(false)}><X size={20} /></button></div><nav>{navItems.map(([id, label, Icon]) => <button key={id} className={page === id ? "nav-link active" : "nav-link"} onClick={() => { setPage(id); setMobileNav(false); }}><Icon size={18} />{label}</button>)}</nav><button className="nav-link logout" onClick={() => setToken("")}><LogOut size={18} />Sign out</button></aside><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setMobileNav(true)}><Menu size={22} /></button><div className="topbar-spacer" /><span className="admin-pill">Administrator</span><div className="admin-avatar">A</div></header><div className="content">{Page}</div></main></div>; }

createRoot(document.getElementById("root")).render(<App />);